%w(
  base
  user
  audio
  photo_size
  document
  sticker
  video
  voice
  contact
  location
  chat
  message_entity
  venue
  message
  input_message_content
  input_contact_message_content
  input_location_message_content
  input_text_message_content
  input_venue_message_content
  inline_keyboard_button
  inline_keyboard_markup
  inline_query
  inline_query_result_article
  inline_query_result_audio
  inline_query_result_cached_audio
  inline_query_result_cached_document
  inline_query_result_cached_gif
  inline_query_result_cached_mpeg4_gif
  inline_query_result_cached_photo
  inline_query_result_cached_sticker
  inline_query_result_cached_video
  inline_query_result_cached_voice
  inline_query_result_contact
  inline_query_result_document
  inline_query_result_gif
  inline_query_result_location
  inline_query_result_mpeg4_gif
  inline_query_result_photo
  inline_query_result_venue
  inline_query_result_video
  inline_query_result_voice
  chosen_inline_result
  callback_query
  update
  keyboard_button
  reply_keyboard_markup
  reply_keyboard_hide
  force_reply
  file
).each do |type|
  require "telegram/bot/types/#{type}"
end
